<<: !include ../common.yaml

esphome:
  name: ${device}
  platform: ESP8266
  board: esp8285
  arduino_version: 2.4.2

logger:

sensor:
  - <<: !include ../sensor/uptime.config.yaml
  - <<: !include ../sensor/wifi_signal.config.yaml

binary_sensor:
  - <<: !include ../binary_sensor/connection_status.config.yaml
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    internal: true
    id: button
    on_press:
      - switch.toggle: relay

switch:
  - <<: !include ../switch/restart.config.yaml
  - platform: gpio
    name: "${name} Relay"
    pin: GPIO12
    id: relay