substitutions:
  device: rgb_light
  name: RGB Light
  ip: 192.168.1.68

esphome:
  name: ${device}
  platform: ESP8266
  board: nodemcuv2

<<: !include common/common.yaml

logger:

light:
  - platform: rgb
    name: ${name}
    restore_mode: ALWAYS_OFF
    red: output_component1
    green: output_component2
    blue: output_component3
    effects:
      - random
      - strobe:
          name: Strobe Effect With Custom Values
          colors:
            - state: true
              brightness: 100%
              red: 100%
              green: 90%
              blue: 0%
              duration: 500ms
            - state: false
              duration: 250ms
            - state: true
              brightness: 100%
              red: 0%
              green: 100%
              blue: 0%
              duration: 500ms
      - flicker

output:
  - platform: esp8266_pwm
    id: output_component1
    pin: D5
    max_power: 90%
  - platform: esp8266_pwm
    id: output_component2
    pin: D6
  - platform: esp8266_pwm
    id: output_component3
    pin: D7
