substitutions:
  device: sensor_node
  name: Sensor Node
  ip: 192.168.1.85

esphome:
  name: ${device}
  platform: ESP8266
  board: nodemcu

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  reboot_timeout: 10s
  output_power: 15dB
  manual_ip:
    static_ip: ${ip}
    gateway: !secret wifi_gateway
    subnet: !secret wifi_subnet
  ap:
    ssid: ${device}
    password: !secret wifi_ap_password
captive_portal:

<<: !include common/api.yaml
<<: !include common/ota.yaml

logger:
  
i2c:
  sda: D1
  scl: D2
  scan: True
  id: bus_a
  
sensor:
  - platform: ccs811
    baseline: 0x1477
    eco2:
      name: "eCO2 Value"
    tvoc:
      name: "Total Volatile Organic Compound"
    address: 0x5A
    update_interval: 30s
  - platform: bme280
    temperature:
      name: "Temperature"
      oversampling: 16x
    pressure:
      name: "Pressure"
    humidity:
      name: "Humidity"
    address: 0x76
    update_interval: 30s
  - platform: bh1750
    name: "Light Level"
    address: 0x23
    update_interval: 30s

deep_sleep:
  run_duration: 1min
  sleep_duration: 15min
  id: deep_sleep_1
  
# mqtt:
#   broker: !secret mqtt_broker
#   username: !secret mqtt_user
#   password: !secret mqtt_password
#   on_message:
#     - topic: ${device}/ota_mode
#       payload: 'ON'
#       then:
#         - deep_sleep.prevent: deep_sleep_1
#     - topic: ${device}/sleep_mode
#       payload: 'ON'
#       then:
#         - deep_sleep.enter: deep_sleep_1